---
- import_tasks: check_vars.yml

- name: "Main | Set service destination path"
  set_fact:
    service_artifact_destination_path: "{{ service_root_folder }}/{{ service_name | upper }}/{{ service_version }}"

- name: "Main | Set artifact destination file"
  set_fact:
    service_artifact_destination_file: "{{ service_artifact_destination_folder }}/{{ service_artifact_id }}-{{ service_version }}.{{ service_extension}}"

- name: " Service | Check if use systemd"
  set_fact:
    use_system_d={{ ansible_service_mgr == 'systemd' }}

- debug: var=ansible_distribution_version

- import_tasks: install_service.yml
  when: >
    service_state == 'present'

- meta: flush_handlers

- import_tasks: healthcheck.yml
  when: >
    ((service_healthcheck_urls is defined and
    service_healthcheck_urls|length > 0) or
    (service_healthcheck_ports is defined and
    service_healthcheck_ports|length > 0)) and
    service_state == 'present
